name: lint

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add actionlint problem matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"

    - name: Lint workflows
      uses: docker://rhysd/actionlint@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9 # v1.7.7
      with:
        args: -color

    - name: Lint PowerShell
      shell: pwsh
      run: |
        $settings = Join-Path . "ScriptAnalyzerProfile.ps1"
        Invoke-ScriptAnalyzer `
            -Path . `
            -Recurse `
            -ReportSummary `
            -Settings $settings `
            -EnableExit

    - name: Lint markdown
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: .markdownlint.json
        globs: |
          **/*.md
